name: Exploring Variables and Secrets

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/1 * * * *"
  push:

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    # This job will only execute if it is a part of main branch   
    if: github.ref == 'refs/heads/main' 
    concurrency: 
      group: production deployment
      cancel-in-progress: false
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker Co ntainer
        timeout-minutes: 1
        run:  |
            echo docker run -d -p 4040:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

